[tool.poetry]
name = "zenserp"
version = "0.1.0"
description = "The Python client library for Zenserp."
authors = ["scizorman <tueda1207@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
click = "8.0.1"
requests = "2.25.1"

[tool.poetry.dev-dependencies]
black = "21.5b2"
flake8 = "3.9.2"
isort = "5.8.0"
mypy = "0.812"
pre-commit = "2.13.0"
pytest = "6.2.4"

[tool.poetry.scripts]
zenserp = "zenserp.cli:cli"

[tool.black]
line-length = 120
target-version = ["py39"]

[tool.isort]
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
