[tool.poetry]
name = "zenserp"
version = "0.1.0"
description = "The Python client library for Zenserp."
license = "MIT"
authors = ["scizorman <tueda1207@gmail.com>"]
maintainers = ["scizorman <tueda1207@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/scizorman/zenserp"
repository = "https://github.com/scizorman/zenserp"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = "^3.9"
click = "8.0.1"
requests = "2.25.1"

[tool.poetry.dev-dependencies]
black = "21.5b2"
flake8 = "3.9.2"
isort = "5.8.0"
mypy = "0.900"
pre-commit = "2.13.0"
pytest = "6.2.4"
types-requests = "0.1.9"

[tool.poetry.scripts]
zenserp = "zenserp.cli:cli"

[tool.black]
line-length = 120
target-version = ["py39"]

[tool.isort]
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
